name = "SolidStateDetectors"
uuid = "71e43887-2bd9-5f77-aebd-47f656f0a3f0"
version = "0.4.2"

[deps]
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ParallelProcessingTools = "8e8a01fc-6193-5ca1-a2f1-20776dae4199"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RadiationDetectorSignals = "bf2c0563-65cf-5db2-a620-ceb7de82658c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
ArraysOfArrays = "0.4, 0.5"
Clustering = "0.13, 0.14"
Distributions = "0.21, 0.22, 0.23"
FillArrays = "0.8, 0.9"
Formatting = "0.4"
Interpolations = "0.12"
IntervalSets = "0.3, 0.4, 0.5"
JSON = "0.21"
LaTeXStrings = "1"
ParallelProcessingTools = "0.4"
ProgressMeter = "1.2"
RadiationDetectorSignals = "0.1"
RecipesBase = "0.7, 0.8, 1.0"
Requires = "0.5, 1"
Rotations = "0.12, 0.13, 1.0"
StaticArrays = "0.12"
StatsBase = "0.32, 0.33"
Tables = "0.2, 1"
TypedTables = "1.2"
Unitful = "0.18, 1"
YAML = "0.3, 0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Test", "Unitful"]
