model: ADLChargeDriftModel
phi110: 0Â°
material: Si
drift:
  velocity:
    model: Bruyneel2006
    parameters:
      e100:
        mu0: 1440cm^2/(V*s)
        beta: 0.992
        E0: 7319.44V/cm
        mun: 0cm^2/(V*s)
      e111:
        mu0: 1440cm^2/(V*s)
        beta: 1.075
        E0: 7319.44V/cm
        mun: 0cm^2/(V*s)
      h100:
        mu0: 474cm^2/(V*s)
        beta: 1.181
        E0: 19831.22V/cm
      h111:
        mu0: 474cm^2/(V*s)
        beta: 0.924
        E0: 19831.22V/cm
temperature_dependence:
  reference_temperature: 300K